import styled from 'styled-components';

export const JumbotronConfig = styled.div`

@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Poppins:wght@300;500;600&display=swap'); 

/* font-family: 'Lato', sans-serif;
font-family: 'Poppins', sans-serif; */

/* ----------------------------------------------
 * Generated by Animista on 2023-4-20 11:15:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand-fwd
 * ----------------------------------------
 */

*{
  font-family: 'Roboto Slab', sans-serif;
}

.tracking-in-expand-fwd {
    -webkit-animation: tracking-in-expand-fwd 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    animation: tracking-in-expand-fwd 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}
@-webkit-keyframes tracking-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
    transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

/* ---------------- Botão do Jumbotron  */
.btn1{
  margin-top: 5px;
  padding: 17px 40px;
  border-radius: 40px;
  border: 0;
  background-color: white;
  box-shadow: rgb(0 0 0 / 5%) 0 0 8px;
  letter-spacing: 1.5px;
  text-transform: uppercase;
  font-size: 15px;
  transition: all .5s ease;
  border-radius: 1.75rem;
  color: #f7f7f7;
  background-color: black;
  cursor: pointer;
  text-decoration: none;
  font-weight: 500;
  letter-spacing: 1.0px;
  font-size: 15px;
  transition: all .6s ease;
}
.btn1:hover {
  letter-spacing: 3px;
  background-color: hsl(220deg 80% 48%);
  color: hsl(0, 0%, 100%);
  box-shadow: rgb(200 260 290) 0px 7px 29px 0px;
}
.btn1:active{
  letter-spacing: 3px;
  background-color: hsl(261deg 80% 48%);
  color: hsl(0, 0%, 100%);
  box-shadow: rgb(93 24 220) 0px 0px 0px 0px;
  transform: translateY(10px);
  transition: 100ms;
}
@keyframes tracking-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
    transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

/* MAIN IMAGE */
.main-image {
  height: 600px;
  background-image: url(images/banner2.jpg);
  margin-bottom: 50px;
  position: relative;
  }
  
  .main-image-info {
    padding: 40px;
    position: absolute;
    left: 25px;
    bottom: 25px;
    border-radius: 10px;
   
  }

  .main-image-info h2, h3 {
    /* color: #5C70F0; */
    color: white;
  } 

  .main-image-info p{
    color: #92E7FA;

  }

`;

export default JumbotronConfig;
